export PATH=$PATH:/usr/sbin/:/bin/:/sbin/
export JAVA_HOME=/usr/lib/jvm/java-6-sun
export MOZILLA_FIVE_HOME=/usr/lib64/xulrunner-1.9.2.9
export PATH=$PATH:$JAVA_HOME/bin
export HISTCONTROL=ignoredups
alias cl=clear
alias ls="ls --color=auto -CF"
alias l=ls
alias la="ls -a"
alias ll="ls -l"
alias ..="cd .."

#. /etc/bash_completion

export GREP_OPTIONS='--color=auto'

PS1="[\[\033[0;32m\]\u\[\033[0m\]@\[\033[1;34m\]\h\[\033[0m\] \W]\$ "
