[[ ${-#*i} != ${-} ]] || return

. ~/.bash_tmux
. ~/.bash_aliases
. ~/.bash_exports

if [ -f $(brew --prefix)/etc/bash_completion ]; then
	. $(brew --prefix)/etc/bash_completion
fi

if [ -f $(brew --prefix)/etc/bash_completion.d/git-completion.bash ]; then
	. $(brew --prefix)/etc/bash_completion.d/git-completion.bash
fi

if [ -f $(brew --prefix)/etc/bash_completion.d/git-prompt.sh ]; then
	. $(brew --prefix)/etc/bash_completion.d/git-prompt.sh
fi
