set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

Bundle 'Syntastic'
Bundle 'The-NERD-tree'
Bundle 'The-NERD-Commenter'
Bundle 'ColorSchemeMenuMaker'
Bundle 'Tagbar'
Bundle 'surround.vim'
Bundle 'unimpaired.vim'
Bundle 'Spaceghost/vim-matchit'
Bundle 'scratch.vim'
Bundle 'fugitive.vim'
Bundle 'Align'
Bundle 'SQLUtilities'
Bundle 'mattboehm/vim-unstack'
Bundle 'fatih/vim-go'
Bundle 'Lokaltog/powerline'
Bundle 'closetag.vim'

filetype plugin indent on

syntax enable

set confirm
set autoindent
set hidden

set paste

runtime macros/matchit.vim

autocmd FileType python setlocal expandtab
autocmd FileType java,c setlocal cindent
autocmd FileType text setlocal tw=70

let mapleader=","

set sw=4
set ts=4
set incsearch
set scrolloff=3

set ignorecase
set smartcase
set wildignore=*.o,*.obj,*.bak,*.exe,*.class

set wildmenu
set wildmode=list:longest
set showcmd

map <F2> w
map <silent> <F3> :bn<CR>
map <silent> <F4> :tabn<CR>
map <silent> <F5> :TagbarToggle<CR>
map <silent> <F6> :cn<CR>
map <silent> <F7> :cp<CR>

nmap <C-n> :bnext<CR>
nmap <C-p> :bprev<CR>


nmap \l :setlocal number!<CR>
nmap \o :set paste!<CR>

cmap w!! w !sudo tee % >/dev/null<CR>:e!<CR><CR>

set mps+=':'
set mps+=<:>

nnoremap Q gqap
vnoremap Q gq

vnoremap <C-r> "hy:%s/<C-r>h//gc<left><left><left>
